services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: surveydb
      MYSQL_USER: surveyuser
      MYSQL_PASSWORD: surveypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: surveyuser
      PMA_PASSWORD: surveypassword
    ports:
      - "8081:80"

  api:
    build: ./surveytool
    container_name: api-container
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/surveydb
      SPRING_DATASOURCE_USERNAME: surveyuser
      SPRING_DATASOURCE_PASSWORD: surveypassword
    ports:
      - "8080:8080"

  frontend:
      build: ./website
      container_name: frontend-container
      restart: always
      depends_on:
        - api
      ports:
        - "8082:80"
      environment:
        VUE_APP_API_URL: http://localhost:8080 

volumes:
  db_data:
